class IntakeForm < ActiveRecord::Base
  attr_accessible :intake_type,:intake_status,:user_id
  belongs_to :user
  has_one :counseling,:dependent => :destroy
  has_one :medical,:dependent => :destroy
  has_one :personal,:dependent => :destroy
  has_many :client_availabilities,:dependent => :destroy
  has_one :reduced_fee,:dependent => :destroy
  has_one :minor,:dependent => :destroy
  has_many :notes, :as => :notable
  has_one :case
  has_one :document,:dependent => :destroy
  has_many :appointments,:dependent => :destroy
  has_many :case_intake_forms,:dependent => :destroy
  def self.all_information(intake_id)
    @intake_form = IntakeForm.find(intake_id)
    if @intake_form.intake_type == 'minor'
      joins("left join minors on minors.intake_form_id = intake_forms.id").joins("left join users on users.id = intake_forms.user_id").joins("left join personals on personals.intake_form_id = intake_forms.id").joins("left join medicals on medicals.intake_form_id = intake_forms.id").where("intake_forms.id = #{intake_id}").select("intake_forms .*,concat(users.first_name,' ',users.last_name) as name,users.address as address,users.city as city,users.state as state,users.zipcode as zip,users.gender as gender,users.date_of_birth as date_of_birth,users.contact_name as contact_name,users.contact_phone as contact_no,users.relationship as relationship,users.contact_email as contact_email,minors.following_areas_child_prob as current_problems,minors.date_of_marriage as date_of_marriage,'' as date_of_seperation,minors.marital_status as marital_status,minors.m_lives_with as living_with,personals.no_of_marriages as no_of_marriages,personals.annual_income as annual_income,personals.occupation as occupation,personals.field_of_study as field_of_study,personals.school as school,personals.degree as degree,personals.student_status as status,personals.employer as employer,personals.time_with_current_emp as time_with_current_emp,personals.believe_in_god as believe_in_god,personals.religious_preference as religious_preference,personals.current_church as current_church,personals.member_of_redeemer_church as member_of_redeemer_church,personals.day_to_day_activity as day_to_day_activity,medicals.rate_your_child_p_health as rate,medicals.hospitalized_for_physical_purposes as hospitalized,medicals.hospital_location_and_dates as h_explain,medicals.child_before_counseling as counseling_before,medicals.reason as p_explain,medicals.gain_from_counseling as gain_from_counseling,medicals.date_of_last_p_exam as date_of_last_p_exam,medicals.e_physical_problems as e_physical_problems,medicals.p_explain as c_explain,medicals.id as medical_id")
    else
      joins("left join counselings on counselings.intake_form_id = intake_forms.id").joins("left join users on users.id = intake_forms.user_id").joins("left join personals on personals.intake_form_id = intake_forms.id").joins("left join medicals on medicals.intake_form_id = intake_forms.id").where("intake_forms.id = #{intake_id}").select("intake_forms .*,concat(users.first_name,' ',users.last_name) as name,users.address as address,users.city as city,users.state as state,users.zipcode as zip,users.gender as gender,users.date_of_birth as date_of_birth,users.contact_name as contact_name,users.contact_phone as contact_no,users.relationship as relationship,users.contact_email as contact_email,counselings.areas_of_problems as current_problems,personals.date_of_marriage as date_of_marriage,personals.date_of_seperation as date_of_seperation,personals.marital_status as marital_status,personals.no_of_marriages as no_of_marriages,personals.annual_income as annual_income,personals.school as school,personals.field_of_study as field_of_study,personals.degree as degree,personals.student_status as status,personals.living_with as living_with,personals.occupation as occupation,personals.employer as employer,personals.time_with_current_emp as time_with_current_emp,personals.believe_in_god as believe_in_god,personals.religious_preference as religious_preference,personals.current_church as current_church,personals.member_of_redeemer_church as member_of_redeemer_church,personals.day_to_day_activity as day_to_day_activity,medicals.rate_your_current_p_health as rate,medicals.hospitalized_for_physical_purposes as hospitalized,medicals.hospital_location_and_dates as h_explain,medicals.counseling_before as counseling_before,medicals.results_of_previous_counseling as p_explain,medicals.gain_from_counseling as gain_from_counseling,medicals.date_of_last_p_exam as date_of_last_p_exam,medicals.e_physical_problems as e_physical_problems,medicals.p_explain as c_explain,medicals.id as medical_id")
    end
  end
end
